### ISSUE TITLE
Complex Exponentiation Error in SCC Monte Carlo Calculation

### ISSUE THREAD

**Issue by lrennels** [rffscghg/MimiGIVE.jl#21]
Copying from Mimi Framework https://forum.mimiframework.org/t/complex-exponentiation-error-in-scc-monte-carlo-calculation/241 for continued conversation.

---

When running a 10,000-trial Monte Carlo SCC simulation with a modified version of MimiGIVE, I run into an error part of the way through the trials: “DomainError with -0.988…[more decimals]: Exponentiation yielding a complex result requires a complex argument.”

There is a stacktrace, but it’s not particularly informative as far as I can tell. In one of the MC iterations, the SCC calculation is requiring an imaginary/complex number (as a result of taking a square root of a negative, maybe?) and breaking. One of the elements of the stacktrace mentions a variable that includes :prtp and :eta, so it’s possible that this is occurring during some calculation involving a discount rate.

Changing the number of iterations to 1,000 avoids the problem, potentially since it doesn’t reach the particular trial that triggers it. Going back to 10,000 but changing the seed yields the same error, but on a different negative number and on a different trial.

Has anyone run into this kind of error before? Are there ways to avoid it?

**Comment by lrennels** [comment]
Hi @christophercallahan your interpretation here is likely correct.  That `DomainError` about `complex result requires a complex argument` generally comes from something like taking the square root of a of a negative, and to be more specific as you point out it often occurs in the discounting calculation in the `post_trial_function` of the Monte Carlo Simulation, likely in the Ramsey discounting formula here:

```
df = [((cpc[year_index]/cpc[i])^dr.eta * 1/(1+dr.prtp)^(t-year) for (i,t) in enumerate(_model_years) if year<=t<=last_year)...]
```

Looking at that formula, and the fact you are adding a damage function, I would presume something in your damage function might be causing (in extreme outlier cases, given as you say it only happens a few times 10k trials) consumption per capita to go negative, and thus `((cpc[year_index]/cpc[i])` becomes negative. The stack trace of your error should point to a line of code.

First off, you should feel free to use a seed (`Random.seed(1234)` to run the same mcs every time, I recommend setting the seed right before `compute_scc`.  This is not completely fool proof over time, it can change in Julia versions or OS in some cases etc., but for a local machine it's quite dependable.

In terms of debugging, what I have done in this case is to some information about the runs in the `save_list`, for example the `fair_id` and the `rffsp_id`, and then add a `try .. catch` block to the computation such that if there is an error, the scc returned is something like `-999`.  Then you can go through your results, look for `-999`, and then take al look at the corresponding `fair_id` and `rffsp_id`.  You can set those manually for a single deterministic run of a model, and that is normally enough to recover the error (those are major sources of uncertainty, although not all of the uncertainty) and QC it.

For the sake of simplicity, I am going to move any further conversation about behavior of, and debugging of, MimiGIVE to an issue here: since further discussion will likely be very model-specific.

**Comment by ccallahan45** [comment]
Hi Lisa, thanks a lot for looking into this! This all makes total sense to me. I played around with different seeds and found one that didn't throw this error even with 10k simulations, so at least have been able to proceed with initial analysis. Of course, that is a bit of an ad hoc workaround, so when finalizing our work I'll take your advice and find the specific parameters that are generating the negative consumption. (Our new damage functions are large, but shouldn't be *that* large -- it's certainly an edge case regardless.)

Thanks again!

**Comment by lrennels** [comment]
Great news! Yes, sounds like an extreme outlier case, when you're at a stage where you'd like to do robust checks on those outliers feel free to reach out again for assistance but your approach sounds great for moving forward now.
