### ISSUE TITLE
slr_damages csv output

### ISSUE THREAD

**Issue by hforew** [rffscghg/MimiGIVE.jl#50]
In estimate_give_scghg.jl, when I set n=2 and save_slr_damages = true---within MimiGIVE.compute_scc()---the two attached files are generated, slr_damages_base_lim_counts and slr_damages_modified_lim_counts. Output only appears for country = BRN and for select years. 

I am aiming to view the sea level rise damages, analogous to those output for heat-related mortality as DamageAggregator_cromar_mortality_damage.csv. 

Is this the incorrect approach? Instead should I follow the procedure under section "2b. Append Offline MimiCIAM Coupling" of https://github.com/rffscghg/MimiGIVE.jl? 

Thank you

[slr_damages_modified_lim_counts.csv](https://github.com/user-attachments/files/15540487/slr_damages_modified_lim_counts.csv)
[slr_damages_base_lim_counts.csv](https://github.com/user-attachments/files/15540488/slr_damages_base_lim_counts.csv)

**Comment by hforew** [comment]
As an update, I have found detail I was searching for in slr_damages.csv. I'm unsure of the output contained in the two CSV files attached to this issue. But please feel free to close.

**Comment by lrennels** [comment]
Hi @hforew I apologize for the delay, and am glad you found what you're looking for. As you saw in your message, CIAM is coupled after the model is run (something we'd like to work on to make things smoother), so it is a bit more difficult to save out particular variables etc. like we can with the `save_list`.

The `slr_damages.csv` files should give you the analogous ones you are looking for, but feel free to be in touch if you have any further questions!
