### ISSUE TITLE
GIVE model - how to retrieve additional series

### ISSUE THREAD

**Issue by museaoide** [rffscghg/MimiGIVE.jl#63]
@lrennels - Hello! Is there a way to

1. retrieve country level GDPs from the socioeconomic module? I think it would be (:PerCapitaGDP, :gdp)? [Link](https://github.com/rffscghg/MimiGIVE.jl/blob/main/src/components/PerCapitaGDP.jl)

2. retrieve agricultural, energy, mortality, and slr damages from the Damages module? (Currently, we see that compute_disaggregated_values=true disaggregates into agricultural, and everything else; can we go more granular?) 

I think for the the first three, this would be (:DamageAggregator, :damage_cromar_mortality), (:DamageAggregator, :damage_ag), (:DamageAggregator, :damage_energy)? [Link](https://github.com/rffscghg/MimiGIVE.jl/blob/main/src/components/DamageAggregator.jl)

However, I do not see how to get the SLR damages. 

3. retrieve temperature as the temperature deviation in C from the 1850-1900 average.
I believe it would be (:TempNorm_1850to1900 , :global_temperature)? [Link](https://github.com/rffscghg/MimiGIVE.jl/blob/main/src/main_model.jl)

Also, just wanted to confirm that the following are true of the basic GIVE model

1. when computing the time t discount rate implied by the ramsey model, the growth rate "g" is the average growth rate in the net consumption series (gdp - damages) from time t=0 to time t?

2. the net consumption series is simply gdp - damages, where gdp per capita series are generated by the Mueller model and damages are generated by the ag, mortality, energy, slr damage functions? 

3. the gdp series from the socioeconomic module don't explicitly take into account climate damages except via what might be in the historical data used to calibrate the Mueller model? 

4. the GIVE model is sequential? That is, there are no feedbacks? 

5. If I'm reading the documentation correctly, a pulse_size = 1. is equal to 1Gt of C for CO2, 1Mt of CH4, and 1Mt of N2O so in carbon dioxide equivalents this would be 1Gt + 1Mt * 25 + 1Mt *298 based on the conversion factors for CH4 and N2O into CO2e? In which case, to get the SCC of carbon after running the model with a pulse_size = 1., I would have to get the present value of marginal damages and divide it by 1Gt + 1Mt * 25 + 1Mt *298? 

6. one way to approximate the scc with a constant 3% discount rate would be to sum the present value of the marginal damage series produced from the model (md_ag + md_noag), correct? 

Thank you in advance!!

**Comment by museaoide** [comment]
@lrennels - Sorry to bother you, but I was wondering if you could help us confirm our understanding of model output!

**Comment by lrennels** [comment]
1. retrieve country level GDPs from the socioeconomic module? I think it would be (:PerCapitaGDP, :gdp)? [Link](https://github.com/rffscghg/MimiGIVE.jl/blob/main/src/components/PerCapitaGDP.jl)

_Yes, that's one access point that will work, be careful of dollar year, the `units` flag will give you the information you need._

2. retrieve agricultural, energy, mortality, and slr damages from the Damages module? (Currently, we see that compute_disaggregated_values=true disaggregates into agricultural, and everything else; can we go more granular?) 

_The `compute_disaggregated_values` flag will disaggregate into all four sectors **This is a work in progress flag, it is not used in any publications so it has not been heavily vetted yet.**._

I think for the the first three, this would be (:DamageAggregator, :damage_cromar_mortality), (:DamageAggregator, :damage_ag), (:DamageAggregator, :damage_energy)? [Link](https://github.com/rffscghg/MimiGIVE.jl/blob/main/src/components/DamageAggregator.jl)

_Yes, that would work, again be careful with units._

However, I do not see how to get the SLR damages. 

_As above, the disaggregation works, or you can use `save_slr_damages` in `compute_scc`_ to get some subsets of data._

3. retrieve temperature as the temperature deviation in C from the 1850-1900 average.
I believe it would be (:TempNorm_1850to1900 , :global_temperature)? [Link](https://github.com/rffscghg/MimiGIVE.jl/blob/main/src/main_model.jl)

_Yes._

Also, just wanted to confirm that the following are true of the basic GIVE model

_For most of this please see relevant publications [Comprehensive evidence implies a higher social cost of CO2 Rennert et al. (2022)](https://www.nature.com/articles/s41586-022-05224-9) and [The social cost of carbon: advances in long-term probabilistic projections of population, GDP, emissions, and discount rates Rennert et al. (2022)](https://muse.jhu.edu/pub/11/article/857704/summary?casa_token=mwBeuMV1OXgAAAAA:ajw3FD1DoGyz3Eo1VXA7SBXD7nirWlDcKYF-1WucTaFd7XjDFZjGrPiFuoKXOrpygqKOLISp)[The social cost of carbon: advances in long-term probabilistic projections of population, GDP, emissions, and discount rates](https://muse.jhu.edu/pub/11/article/857704/summary?casa_token=mwBeuMV1OXgAAAAA:ajw3FD1DoGyz3Eo1VXA7SBXD7nirWlDcKYF-1WucTaFd7XjDFZjGrPiFuoKXOrpygqKOLISp)

1. when computing the time t discount rate implied by the ramsey model, the growth rate "g" is the average growth rate in the net consumption series (gdp - damages) from time t=0 to time t?

_See discounting section of the Methods of [Comprehensive evidence implies a higher social cost of CO2 Rennert et al. (2022)](https://www.nature.com/articles/s41586-022-05224-9) and the equation (6)_

3. the net consumption series is simply gdp - damages, where gdp per capita series are generated by the Mueller model and damages are generated by the ag, mortality, energy, slr damage functions? 

4. the gdp series from the socioeconomic module don't explicitly take into account climate damages except via what might be in the historical data used to calibrate the Mueller model? 

_See publications on the RFF-SPs [The social cost of carbon: advances in long-term probabilistic projections of population, GDP, emissions, and discount rates Rennert et al. (2022)](https://muse.jhu.edu/pub/11/article/857704/summary?casa_token=mwBeuMV1OXgAAAAA:ajw3FD1DoGyz3Eo1VXA7SBXD7nirWlDcKYF-1WucTaFd7XjDFZjGrPiFuoKXOrpygqKOLISp)[The social cost of carbon: advances in long-term probabilistic projections of population, GDP, emissions, and discount rates](https://muse.jhu.edu/pub/11/article/857704/summary?casa_token=mwBeuMV1OXgAAAAA:ajw3FD1DoGyz3Eo1VXA7SBXD7nirWlDcKYF-1WucTaFd7XjDFZjGrPiFuoKXOrpygqKOLISp)

6. the GIVE model is sequential? That is, there are no feedbacks? 

7. If I'm reading the documentation correctly, a pulse_size = 1. is equal to 1Gt of C for CO2, 1Mt of CH4, and 1Mt of N2O so in carbon dioxide equivalents this would be 1Gt + 1Mt * 25 + 1Mt *298 based on the conversion factors for CH4 and N2O into CO2e? In which case, to get the SCC of carbon after running the model with a pulse_size = 1., I would have to get the present value of marginal damages and divide it by 1Gt + 1Mt * 25 + 1Mt *298? 

8. one way to approximate the scc with a constant 3% discount rate would be to sum the present value of the marginal damage series produced from the model (md_ag + md_noag), correct?

_The model allows you to enter you own discount rate. Constant 3% would have an eta parameter of 0. and a prtp parameter of 0.03._

**Comment by lrennels** [comment]
@museaoide thank you for the inquiry, closing Issue now after answering these questions
