### ISSUE TITLE
From Forum: Deterministic SCC Result

### ISSUE THREAD

**Issue by lrennels** [rffscghg/MimiGIVE.jl#70]
**moved from forum**

https://forum.mimiframework.org/t/first-time-user-calibration-of-scc-estimates/313

I am a first-time user and trying to get acquainted with both Julia and MimiGIVE. I was able to install Juia, add packages and run the default model. However, when I run the default model, I got result that seemed far too low. I was expecting to get something closer to the $185/ton that is found the SCC explorer tool. Any tips for calibrating my model to make sure it’s running correctly? I was following sections 2a (fully coupled model) and 4a (deterministic scc calculation) on the Github repository.

scc = MimiGIVE.compute_scc(year=2020)
26.166523152489944

scc = MimiGIVE.compute_scc(year=2030)
38.34888259268095

**Comment by lrennels** [comment]
Good question! Our deterministic SCC calculation calculates the SCC based on one set of parameters, but _it is not a central value of the full distribution_, since many of the key uncertainty parameters, like the socioeconomic pathway and the climate model parameter set, do not have a "central" run. What you're doing is correct, and your confusion is fair! In order to get the reported value (within the standard error) you'll need to run a Monte Carlo. The deterministic calculation can be helpful for testing, debugging, etc. but will not give a sense for the central tendency of the full distribution.

**Comment by lrennels** [comment]
Hi @afoxwolfe

Your work looks great here, and the code looks correct to me. I think the pesky difference you are seeing is that results are reported in USD $2005. In the Nature paper code you will see a file called price_level_inflator.jl with
```
const pricelevel_2005_to_2020 = 113.648 / 87.504
```
plugging that in you'd have an expected SCC of about $188.30 for an n of 1,000 (which is a good n value to do your iterations, we use n of 10k for final runs but 1k tends to be enough for iterative work).

MimiCIAM is automatically coupled in for the `compute_scc` function, so you're all good there. It isn't when you do a more simple `get_model` --> `run_model` call.

**Comment by lrennels** [comment]
Per the country-by-country damages, by damage function GIVE produces

- Agriculture at the FUND region level (16 regions) ([Moore et al., 2017](https://www.nature.com/articles/s41467-017-01792-x))
- Mortality and Energy at the country level (184 countries) ([Cromar et al., 2022](https://pubmed.ncbi.nlm.nih.gov/35073249/) and [Clarke et al., 2018](https://www.sciencedirect.com/science/article/pii/S0140988318300112))
- Sea-level rise at the segment level (~12k coastal segments from the DIVA database) (Diaz 2016)[https://link.springer.com/article/10.1007/s10584-016-1675-4])

You can get a general sense for the distribution of impacts from the individual papers for each, if you don't want to rerun the model, since they all contain some description of the distribution. If you do want to get the actual damage values from the GIVE model there is some support for that that I can point you too -- it is just a bit memory intensive (large files are produced) so if it's for a class it could be easier to use the visuals from the respective papers -- but I'm happy to point you to the MimiGIVE functionality if you'd like to do that!

**Comment by lrennels** [comment]
@afoxwolfe Assuming your questions here have been answered I'll close this for now, but be in touch with follow ups -- either with a new issue or if it's linked to these questions just make sure to @ me so I see it

**Comment by sleepguyjin** [comment]
Hello both @lrennels , thank you so much for developing a very helpful interaction here. I was wondering if I may jump in, as I am also interested in the analysis on a country-by-country basis, and the motivation seems quite related. Please let me know if I should start a new thread.

When playing around with the MCS SCC, I added the compute_disaggregated_values flag, but I got an error message that indicates that this flag is unsupported (yet). This seems related to the fact that this is in a beta version, as suggested in the readme, and also related to your comment that country-level damage values are quite memory-intensive, in particular for many MCS runs. Would it be possible to access the country-level SCCs ---along with their RFF-SP- emissions--- by adding some tweaks to these lines? (N.B. Without this particular flag, the code seems to be working.)

```
using Mimi
using MimiGIVE

discount_rates = [(label="Ramsey", prtp=0.015, eta=1.45), (label="Constant 2%", prtp=0.02, eta=0.)]

result = MimiGIVE.compute_scc(year = 2020, discount_rates = discount_rates, n = 5, compute_disaggregated_values = true)

```
